#!/bin/bash

# 변수
# $1: 계정이름
# $2: 계정 패스워드
# $3: DB이름
# $4: DB 계정
# $5: DB 비밀번호
# $6: DB root 이름
# $7: DB root 비밀번호

current_date=$(date +"%Y-%m-%d")

# 임시파일 생성 (고유한 이름으로)
vhost_temp=$(mktemp /tmp/vhosts.conf_tempfile.XXXXXX)
cband_temp=$(mktemp /tmp/cband.conf_tempfile.XXXXXX)
db_temp=$(mktemp /tmp/db.create.conf_tempfile.XXXXXX)

# 사용자 생성 및 패스워드 설정
/usr/sbin/useradd -m -s /bin/bash -d /home/$1 -g www $1
echo "$1:$2" | chpasswd  # chpasswd 명령으로 패스워드 설정

# 용량 설정
edquota -p test7 -u $1

# 홈페이지 디렉토리 생성 및 설정
chmod 701 /home/$1
mkdir -p /home/$1/www
chmod 755 /home/$1/www
chown $1:www /home/$1/www
mkdir /etc/httpd/logs/vhosts/$1
chmod 755 /etc/httpd/logs/vhosts/$1

# 인덱스 파일 추가
echo "$1.web2002.kr" >> /home/$1/www/index.html
chown $1:www /home/$1/www/index.html

# 가상 호스트 설정
{
    echo ""
    echo "# == $1 # $current_date =="
    echo "<VirtualHost *:80>"
    echo "    ServerAdmin webmaster@"   
    echo "    DocumentRoot /home/$1/www"   
    echo "    ServerName $1.web2002.kr"   
    echo "    ServerAlias $1.web2002.kr"    
    echo "    <Directory /home/$1/www>"  
    echo "        Options -ExecCGI   "  
    echo "        AllowOverride All   "  
    echo "        Order Deny,Allow   "  
    echo "        Allow from all   "  
    echo "        Require all granted   "  
    echo "        RMode config   "
    echo "        RUidGid $1 www   "
    echo "    </Directory>   "  
    echo "    ErrorLog logs/vhosts/$1/$1-error_log" 
    echo "    CustomLog logs/vhosts/$1/$1-access_log combined"
    echo "      php_admin_flag display_errors Off "  
    echo "      php_admin_flag allow_url_fopen Off "  
    echo "      php_admin_flag register_globals Off "  
    echo "      php_admin_flag magic_quotes_gpc Off "  
    echo "      php_admin_flag safe_mode Off "  
    echo "      php_admin_flag session.auto_start Off "  
    echo "      <IfModule cband_module> "  
    echo "          CBandUser cband$1"  
    echo "      </IfModule> "  
    echo "      RewriteEngine On "  
    echo "      RewriteCond %{REQUEST_METHOD} ^(TRACE|TRACK) "  
    echo "      RewriteRule .* - [F] "  
    echo "      RewriteCond %{REQUEST_URI} ^/error/509.html$  "  
    echo "      RewriteRule ^ http://web2002.co.kr/traffic/index.htm [R=302,L,E=nocache:1]  "  
    echo "      Include conf/nobots.conf  "  
    echo "      <IfModule security2_module>  "  
    echo "          Include conf/modsec_rules/modsecurity-middle.conf  "  
    echo "          SecRuleEngine On  "  
    echo "      </IfModule>"  
    echo "</VirtualHost>" 
    echo "# == $1 # $current_date =="
} >> $vhost_temp

cp -arp /etc/httpd/conf.d/vhosts.conf /etc/httpd/conf.d/vhosts.conf.old
cat $vhost_temp >> /etc/httpd/conf.d/vhosts.conf

# CBand 설정
{
    echo ""
    echo "# == cband$1 # $current_date =="
    echo "<IfModule cband_module>"
    echo "  <CBandUser cband$1>"
    echo "     CBandUserLimit 3Gi"
    echo "     CBandUserPeriod 1D"
    echo "     <Location /throttle-me>"
    echo "       SetHandler cband-status-me"
    echo "       AuthName 'cband-status-me'"
    echo "       AuthType Basic"
    echo "       AuthUserFile /usr/local/apache/conf/.$1"
    echo "       require user $1"
    echo "     </Location>"
    echo "  </CBandUser>"
    echo "</IfModule>"
    echo "# == cband$1 # $current_date =="
} >> $cband_temp

cp -arp /etc/httpd/conf.d/cband.conf /etc/httpd/conf.d/cband.conf.old
cat $cband_temp >> /etc/httpd/conf.d/cband.conf

# MySQL DB 및 사용자 생성
{
    echo "CREATE DATABASE IF NOT EXISTS $3;"
    echo "DROP USER IF EXISTS '$4'@'%';"
    echo "DROP USER IF EXISTS '$4'@'localhost';"
    echo "CREATE USER '$4'@'%' IDENTIFIED BY '$5';"
    echo "CREATE USER '$4'@'localhost' IDENTIFIED BY '$5';"
    echo "GRANT ALL PRIVILEGES ON $3.* TO '$4'@'%' IDENTIFIED BY '$5';"
    echo "GRANT ALL PRIVILEGES ON $3.* TO '$4'@'localhost' IDENTIFIED BY '$5';"
    echo "FLUSH PRIVILEGES;"
} >> $db_temp

mysql -u "$6" -p"$7" < "$db_temp"

# Apache 설정 테스트
/usr/sbin/httpd -t
if [ $? -eq 0 ]; then
    echo "Apache 설정에 문제가 없습니다."
    # /usr/sbin/httpd -k restart
else
    echo "Apache 설정에 오류가 있습니다."
    exit 1
fi

# 임시 파일 삭제
rm -rf $vhost_temp $cband_temp $db_temp